# Generated by Django 4.1.3 on 2026-07-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_collector', '0007_widen_ban_source_and_seed_missing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientanalytic',
            options={'verbose_name': 'UI event', 'verbose_name_plural': 'UI events'},
        ),
    ]
