# Generated by Django 4.1.3 on 2026-07-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_widen_ban_source_and_seed_missing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionconfig',
            options={'verbose_name': 'action settings snapshot', 'verbose_name_plural': 'action settings snapshots'},
        ),
        migrations.AlterModelOptions(
            name='eksisozlukentry',
            options={'verbose_name': 'Ekşi Sözlük entry', 'verbose_name_plural': 'Ekşi Sözlük entries'},
        ),
        migrations.AlterModelOptions(
            name='eksisozluktitle',
            options={'verbose_name': 'Ekşi Sözlük title', 'verbose_name_plural': 'Ekşi Sözlük titles'},
        ),
        migrations.AlterModelOptions(
            name='eksisozlukuser',
            options={'verbose_name': 'Ekşi Sözlük user', 'verbose_name_plural': 'Ekşi Sözlük users'},
        ),
    ]
